name: Update data and translate

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually  
  push:
    branches: [feat/use-free-db-as-source]

jobs:
  update-data-and-translate:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm-install
        run: npm install
      - name: update-data-and-translate
        run: npm run build:update-data-and-translate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FREE_DB_USERNAME: ${{ secrets.FREE_DB_USERNAME }}
          FREE_DB_PASSWORD: ${{ secrets.FREE_DB_PASSWORD }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: added new data and updated changed data incl. translations"
          branch: "my-test-branch-123"
